### ISSUE TITLE
Extending enum with literal types

### ISSUE THREAD

**Issue by valenterry** [julienrf/enum#10]
Often I have the case that I have a sealed trait with case classes or objects and I need to encode them into primitive types like Strings, Ints, ... or decode them from these primitives, sometimes statically. Now when I name my classes/objects exactly like the primitives they should be encoded into, this works fine. But quite often I have want to declare a custom mapping. More so if I don't have the class names under my control.

I think it would be possible to extend this library to support a 1 on 1 mapping between literal types and real enum types, making it an error at compiletime if one messes up and uses e.g. the same string (with same literal type) twice or more for the same enum.

It could also work together with e.g. play-json-derived-codecs.

What do you think about this idea?

**Comment by julienrf** [comment]
Hi,

If you want to have control on the mapping you can define a custom `Encoder` for your enum. But currently that works only for a `String` encoding.

**Comment by valenterry** [comment]
Hi @julienrf thanks for your answer!

You are right in that for doing Encoding I can create my own `Encoder`. However, for decoding this is not possible. Well, unless I write a custom `Enum`. And this is not all. Consider this code:

``` scala
sealed trait Foo
object Foo {
  case object Bar extends Foo
  case object Baz extends Foo
}

implicit val barEncoder: Encoder[Foo.Bar.type] = new Encoder[Foo.Bar.type] {
  override def encode(bar: Foo.Bar.type): String = "Christmastree"
}

implicit val bazEncoder: Encoder[Foo.Baz.type] = new Encoder[Foo.Baz.type] {
  override def encode(baz: Foo.Baz.type): String = "Christmastree"
}

val enc: Encoder[Foo] = // use barEncoder and bazEncoder
enc.encode(Foo.Bar) // "Christmastree"
enc.encode(Foo.Baz) // "Christmastree"
```

This works as expected. But I would like to have some Encoder - let's call it `DistinctEncoder` - which guarantees me at compiletime that it will encode every type to a different literal (with distinct literal types). I would like to have something like that for Decoding, too. Creating a `DistinctEncoder[Foo]` should be impossible if it consinsts of one or more encoders that encode to the same literal type.

Of course I am not asking you to do this but I am willing to contribute this functionality. But first I want to make sure that you like the idea itself and also to put it into this project.

**Comment by julienrf** [comment]
> However, for decoding this is not possible

Could you elaborate why?

> This works as expected. But I would like to have some Encoder - let's call it DistinctEncoder - which guarantees me at compiletime that it will encode every type to a different literal (with distinct literal types)

This would be a nice feature but I’m worried that the added complexity would not make the feature worth it. I don’t want to discourage you to try to implement it, though ^^ You should give it a try!

**Comment by valenterry** [comment]
> Could you elaborate why?

I didn't find a way to do that without implementing a custom `Enum`. Maybe I missed something?

> give it a try!

Let's see what we can do. :)

**Comment by julienrf** [comment]
> I didn't find a way to do that without implementing a custom Enum. Maybe I missed something?

Indeed I just tried and noticed that the derived encoder is always picked even though one explicitly defines a custom encoder. I’ll create an issue for that.

**Comment by valenterry** [comment]
Actually I just noticed that Enumeratum already got such a feature. Not sure if I want to spend the time on recreating it. I will close this for now. :)
